// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOwAgznKr79FHziZpGgxSAHTASoaEhfHk',
    appId: '1:775898729605:web:abcdef123456789',
    messagingSenderId: '775898729605',
    projectId: 'diet-app-501bb',
    authDomain: 'diet-app-501bb.firebaseapp.com',
    storageBucket: 'diet-app-501bb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOwAgznKr79FHziZpGgxSAHTASoaEhfHk',
    appId: '1:775898729605:android:b066bc2c7759d781246dec',
    messagingSenderId: '775898729605',
    projectId: 'diet-app-501bb',
    storageBucket: 'diet-app-501bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOwAgznKr79FHziZpGgxSAHTASoaEhfHk',
    appId: '1:775898729605:ios:abcdef123456789',
    messagingSenderId: '775898729605',
    projectId: 'diet-app-501bb',
    storageBucket: 'diet-app-501bb.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOwAgznKr79FHziZpGgxSAHTASoaEhfHk',
    appId: '1:775898729605:macos:abcdef123456789',
    messagingSenderId: '775898729605',
    projectId: 'diet-app-501bb',
    storageBucket: 'diet-app-501bb.firebasestorage.app',
    iosBundleId: 'com.example.deneme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOwAgznKr79FHziZpGgxSAHTASoaEhfHk',
    appId: '1:775898729605:windows:abcdef123456789',
    messagingSenderId: '775898729605',
    projectId: 'diet-app-501bb',
    storageBucket: 'diet-app-501bb.firebasestorage.app',
  );
} 